parameters:
    pydev_imageeditor.form.type.editimage.class: 'PyDev\ImageEditorBundle\Form\Type\EditImageType'

services:
    form.type.edit_image:
        class: "%pydev_imageeditor.form.type.editimage.class%"
        arguments:
            - "@kunstmaan_media.media_manager"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: edit_image }
